yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('tech/', views.TechAuthor.as_view(), name='tech'),
    path('author/', views.AboutAuthor.as_view(), name='author')

]

yatube/post/urls.py
from django.urls import path

from . import views

app_name = 'post'
urlpatterns = [
    path('', views.index, name="main"),
    path('group/<slug:group_name>/', views.group_posts, name='group'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('posts/create/', views.CreatePostView.as_view(), name='post_create'),
    path("posts/<int:post_id>/edit/", views.EditPostView.as_view(), name="post_update"),
]

yatube/users/urls.py
from django.contrib.auth.views import LogoutView, LoginView, PasswordChangeView, PasswordChangeDoneView
from django.urls import path

from . import views

app_name = 'users'
urlpatterns = [
    path('logout/', LogoutView.as_view(template_name='users/logged_out.html'), name='logout'),
    path('login/', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('password_change/', PasswordChangeView.as_view(template_name='users/password_change_form.html'),
         name='change_password'),
    path('password_change/done/', PasswordChangeDoneView.as_view(template_name='users/password_change_done.html'),
         name='change_password_done'),

    # path('login/', LoginView.as_view(template_name='users/../templates/registration/login.html'), name='login'),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import path, include

# yatube/url.py
urlpatterns = [
    path('auth/', include('users.urls', namespace='users')),
    path('', include('post.urls', namespace='post')),
    path('admin/', admin.site.urls),
    path('auth/', include('django.contrib.auth.urls')),
    path('library/', include('library.urls', namespace='library')),
    path('about/', include('about.urls', namespace='about')),

]

yatube/templates/includes/footer.html
<footer class="border-top text-center py-3">
    <!-- тег span используется для добавления нужных стилей отдельным участкам текста -->
    <p>© {{ year }} Copyright <span style="color:red">Ya</span>tube</p>
</footer>

yatube/templates/includes/header.html
{% load static %}
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

<meta charset="utf-8"> <!-- Кодировка сайта -->
<!-- Сайт готов работать с мобильными устройствами -->
<meta name="viewport" content="width=device-width, initial-scale=1">
<!-- Загружаем фав-иконки -->
<link rel="icon" href="{% static 'img/fav/favicon.ico' %}" type="image">
<link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/fav/apple-touch-icon.png' %}">
<link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/fav/favicon-32x32.png' %}">
<link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/fav/favicon-16x16.png' %}">
<meta name="msapplication-TileColor" content="#000">
<meta name="msapplication-TileColor" content="#da532c">
<meta name="theme-color" content="#ffffff">
<header>
    <nav class="navbar navbar-light" style="background-color: lightskyblue">
        <div class="container">
            <a class="navbar-brand" href="{% url 'post:main' %}">
                <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
                <span style="color:red">Ya</span>tube
            </a>
            {# Добавлено в спринте #}

            {% comment %}
      Меню - список пунктов со стандартными классами Bootsrap.
      Класс nav-pills нужен для выделения активных пунктов
      {% endcomment %}
            <ul class="nav nav-pills">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'about:author' %}">Об авторе</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url "about:tech" %}">Технологии</a>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url "post:post_create" %}">Новая запись</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link link-light" href="{% url 'users:change_password' %}">Изменить пароль</a>
                    </li>
                    <li class="nav-item">
                        <form method="post" action="{% url 'users:logout' %}">
                            {% csrf_token %}
                            <button type="submit" class="nav-link link-light">Выйти</button>
                        </form>
                        {#                        <a  href="{% url "users:logout" %}">Выйти</a>#}
                    </li>
                    <li>
                        Пользователь: {{ user.username }}
                    <li>
                        {% else %}
                    <li class="nav-item">
                        <a class="nav-link link-light" href="{% url "users:login" %}">Войти</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link link-light" href="{% url "users:signup" %}">Регистрация</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </nav>
</header>