yatube/library/urls.py
from django.urls import path

from . import views

app_name = 'library'

urlpatterns = [
    path('new_book/', views.NewBookView.as_view(), name='new_book'),
    path('book/<slug:book_name>', views.LibraryBookView.as_view()),
    path('', views.LibraryMainView.as_view(), name='main'),
    path("rock/", views.UserCd.as_view(), name='rock')

]

yatube/post/urls.py
from django.urls import path

from . import views

app_name = 'post'
urlpatterns = [
    path('', views.index, name="main"),
    path('group/<slug:group_name>/', views.group_posts, name='group'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('posts/create/', views.CreatePostView.as_view(), name='post_create'),
    path("posts/<int:post_id>/edit/", views.EditPostView.as_view(), name="post_update"),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import path, include

# yatube/url.py
urlpatterns = [
    path('auth/', include('users.urls', namespace='users')),
    path('', include('post.urls', namespace='post')),
    path('admin/', admin.site.urls),
    path('auth/', include('django.contrib.auth.urls')),
    path('library/', include('library.urls', namespace='library')),
    path('about/', include('about.urls', namespace='about')),

]

yatube/library/models.py
from django.db import models
from django.db.models import Choices

genre_choices = {'metalic': 'metalic', 'rap': 'rap'}


# Create your models here.

class Genre(models.Model):
    name = models.CharField(max_length=200)


class Book(models.Model):
    author = models.CharField(max_length=200)
    genre_id = models.ForeignKey(Genre, on_delete=models.SET_NULL, null=True)
    name = models.CharField(max_length=200)
    pages = models.IntegerField()


class CD(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    title = models.CharField(max_length=100)
    artist = models.CharField(max_length=40)
    genre = models.CharField(choices=genre_choices, max_length=100)
    price = models.DecimalField(blank=True, decimal_places=2, max_digits=10**5)
    comment = models.TextField(blank=True)

    """Имя (name), текстовая строка, не более 100 символов.
Электронная почта для обратной связи (email)
Название альбома (title), текстовая строка, не более 100 символов.
Исполнитель (artist), текстовая строка, не более 40 символов.
Жанр (genre), поле выбора из предустановленных значений.
Стоимость (price), числовое поле, десятичные числа; необязательное.
Комментарий (comment), многострочное текстовое поле; необязательное.
"""

yatube/library/forms.py
from django import forms
from .models import Book, CD


class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = ('author', 'genre_id', 'name', 'pages')


class CDForm(forms.ModelForm):
    class Meta:
        model = CD
        fields = ('name', 'email', 'title', 'artist')

    def clean_artist(self):
        data = self.cleaned_data['artist']
        artist = CD.objects.count(data)
        if data not in artist:
            raise forms.ValidationError(
                "Вы не можете передать диск этого автора, потому что у получателя нет ни одного диска от этого автора")
        return data

yatube/library/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.views.generic import CreateView
from django.core.mail import send_mail
from .forms import BookForm, CDForm
from .models import Book


# Create your views here.
class LibraryMainView(View):
    template_name = 'library/library_view.html'

    def get(self, request):
        last_ten_books = Book.objects.all()[:10]
        context = {
            'books': last_ten_books
        }
        return render(request, self.template_name, context)


class NewBookView(CreateView):
    form_class = BookForm
    template_name = 'library/new_book.html'
    success_url = '/thankyou/'


class LibraryBookView(View):
    def get(self, request):
        pass


class UserCd(View):
    form_class = CDForm
    template_name = 'library/index.html'
    success_url = '/thankyou/'

    def get(self, request):
        return render(request, self.template_name, {'form': self.form_class})

    def post(self, request):
        form = CDForm(request.POST)

        if not form.is_valid():
            return
        send_mail('Форма from CD Site',
                  f'Вот ваш данные {form}',
                  'oursite@mail.com',
                  form.cleaned_data['email'],
                  )

yatube/templates/library/index.html
<!DOCTYPE html>
<!-- Based on https://getbootstrap.com/docs/4.4/examples/pricing/ -->
<html lang="ru">
<head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <title>Уголок рокнрольщика</title>

    <!-- Bootstrap core CSS -->
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
</head>
    <body>
        <h1>Предложение обмена</h1>
        <p class="lead">
            Предложите мне свой диск на обмен.
        </p>
        {% if form.errors %}
            {% for field in form %}
                {% for error in field.errors %}
                <div class="alert alert-danger">
                    {{ error|escape }}
                </div>
                {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                    {{ error|escape }}
                </div>
            {% endfor %}
        {% endif %}
        <form method="post" action="/">
            {% csrf_token %}

            {% for field in form %}
            <div class="form-group row my-3 p-3">
                <label for="{{ field.id_for_label }}">
                    {{ field.label }}
                    {% if field.field.required %}
                        <span class="required text-danger">*</span>
                    {% endif %}
                </label>
                {{ field }}
                {% if field.help_text %}
                    <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                    {{ field.help_text|safe }}
                    </small>
                {% endif %}
            </div>
            {% endfor %}
            <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary">
                    Предложить
                </button>
            </div>
        </form>
   </body>
</html>

yatube/templates/library/library_view.html
{% extends 'base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% block content %}
    {% for book in books %}
        <p>{{ book.name }} - {{ book.author }}</p>
    {% endfor %}
{% endblock %}
</body>
</html>

yatube/templates/library/new_book.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form action="{% url 'library:new_book' %}">

    {{ form.as_p }}
    <input type="submit" value="Отправить">
</form>


</body>
</html>

yatube/templates/library/thankyou.html
<!DOCTYPE html>
<!-- Based on https://getbootstrap.com/docs/4.4/examples/pricing/ -->
<html lang="ru">
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <title>Уголок рокнрольщика</title>

    <!-- Bootstrap core CSS -->
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
  </head>

  <body>
  <div class="container">
    <h1>Спасибо</h1>
    <p class="lead">
      Обязательно отвечу на предложение в ближайшее время.
    </p>
  </div>

  </body>
</html>