yatube/post/urls.py
from django.urls import path

from . import views

app_name = 'post'
urlpatterns = [
    path('', views.index, name="main"),
    path('group/<slug:group_name>/', views.group_posts, name='group'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('posts/create/', views.CreatePostView.as_view(), name='post_create'),
    path("posts/<int:post_id>/edit/", views.EditPostView.as_view(), name="post_update"),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import path, include

# yatube/url.py
urlpatterns = [
    path('auth/', include('users.urls', namespace='users')),
    path('', include('post.urls', namespace='post')),
    path('admin/', admin.site.urls),
    path('auth/', include('django.contrib.auth.urls')),
    path('library/', include('library.urls', namespace='library')),
    path('about/', include('about.urls', namespace='about')),

]

yatube/post/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=100)
    address = models.SlugField()
    description = models.TextField()

    def __str__(self):
        return self.title


# Create your models here.
class Post(models.Model):
    text = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='post')
    group = models.ForeignKey(Group, on_delete=models.SET_NULL, blank=True, null=True)

    class Meta:
        ordering = ['-pub_date']

    def __str__(self):
        return self.text

yatube/post/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import Paginator
from django.views.generic import CreateView, UpdateView
from django.urls import reverse

from .models import Post, Group, User
from django.core.mail import send_mail


# Create your views here.

def index(request):
    template = "posts/index.html"

    posts = Post.objects.all().select_related()
    p = Paginator(posts, 10)
    page_number = request.GET.get('page')

    template_page = p.get_page(page_number)
    context = {
        'title': "Это главная страница проекта Yatube",
        'page_obj': template_page,

    }
    return render(request, template, context)


def group_posts(request, group_name):
    template = "posts/group_list.html"
    context = {
        'title': 'Здесь будет информация о группах проекта Yatube',
        'group_name': group_name
    }
    group = get_object_or_404(Group, address=group_name)
    posts = Post.objects.filter(group__address=group_name)
    context['posts'] = posts
    return render(request, template, context)


def profile(request, username):
    username = User.objects.get(username=username)
    con = Post.objects.select_related().filter(author=username)
    p = Paginator(con, 5)
    page = request.GET.get('page')
    context = {'name': username.get_full_name(),
               "page_obj": p.get_page(page),
               "posts_count": con.count(),
               }

    return render(request, template_name='posts/profile.html', context=context)


def post_detail(request, post_id):
    # get user post
    post = Post.objects.select_related("group").get(id=post_id)
    # get instance of user who writes the post
    post_user = User.objects.get(id=post.author_id)
    # join with users and get post's count of this user
    post_count = Post.objects.select_related().filter(author=post_user).count()
    is_author = Post.objects.get(id=post_id, author_id=post.author_id)
    context = {"post": post, "post_count": post_count, "is_author": is_author}

    return render(request, template_name='posts/post_detail.html', context=context)


class CreatePostView(CreateView):
    model = Post
    fields = ("text", "group")
    successful_url = "post:profile"
    template_name = "posts/create_post.html"

    def form_valid(self, form):
        form.instance.author_id = self.request.user.id
        return super().form_valid(form)

    def get_success_url(self):
        return reverse(self.successful_url, kwargs={'username': self.object.author.username})


class EditPostView(UpdateView):
    model = Post
    fields = ["text", "group"]
    template_name = "posts/create_post.html"

    def get(self, request, **kwargs):
        post_id = int(kwargs.get("post_id"))
        post = get_object_or_404(Post, id=post_id)
        if self.request.user.id == post.author_id:
            return render(request, self.template_name, {"form": {
                "group": str(post.group),
                "text": post.text,
            },
                "is_edit": 1
            })
        return redirect("post:post_detail", post_id)

yatube/templates/posts/create_post.html
{% extends "base.html" %}
<!DOCTYPE html>
<html lang="ru">
<head>{% block title %}
    <title>Новый пост</title>
{% endblock %}
</head>
<body>
{% block content %}

    <main>
        <div class="container py-5">
            <div class="row justify-content-center">
                <div class="col-md-8 p-5">
                    <div class="card">
                        <div class="card-header">
                            {% if is_edit %}
                                Редактирование
                            {% else %}
                                Новый пост
                            {% endif %}
                        </div>
                        <div class="card-body">
                            <form method="post" action="{% url "post:post_create" %}">
                                {% csrf_token %}
                                {#                                <input type="hidden" name="csrfmiddlewaretoken" value="">#}
                                <div class="form-group row my-3 p-3">
                                    <label for="id_text">
                                        Текст поста
                                        <span class="required text-danger">*</span>
                                    </label>
                                    <textarea name="text" cols="40" rows="10" class="form-control" required
                                              id="id_text">{% if is_edit %}{{ form.text }}{% endif %}
                                    </textarea>
                                    <small id="id_text-help" class="form-text text-muted">
                                        Текст нового поста
                                    </small>
                                </div>
                                <div class="form-group row my-3 p-3">
                                    <label for="id_group">
                                        Group
                                    </label>
                                    <select name="group" class="form-control" id="id_group">
                                        <option value="">---------</option>
                                        {% for group in groups %}
                                            {% if is_edit and form.group == group.title %}
                                                <option value="{{ forloop.counter }}" selected>Группа: {{ group.title }}
                                                    - {{ group.description }}</option>
                                            {% else %}
                                                <option value="{{ forloop.counter }}">Группа: {{ group.title }}
                                                    - {{ group.description }}</option>
                                            {% endif %}

                                        {% endfor %}
                                    </select>
                                    <small id="id_group-help" class="form-text text-muted">
                                        Группа, к которой будет относиться пост
                                    </small>
                                </div>
                                <div class="d-flex justify-content-end">
                                    <button type="submit" class="btn btn-primary">
                                        {% if is_edit %}
                                            Сохранить
                                        {% else %}
                                            Добавить
                                        {% endif %}
                                    </button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock content %}

</body>
</html>

yatube/templates/posts/group_list.html
{% extends "base.html" %}
{% load static %}
<!DOCTYPE html> <!-- Используется html 5 версии -->
<html lang="ru"> <!-- Язык сайта - русский -->
<head>
    {% block title %}
        <title>{{ title }}</title>
    {% endblock title %}
</head>
<body>
<header>
    {% block content %}
        <!-- Использованы классы бустрапа для создания типовой навигации с логотипом -->


        </header>
        <main>
            <!-- класс py-5 создает отступы сверху и снизу блока -->
            <div class="container py-5">
                <h1>{{ title }}</h1>
                <p>
                    {{ description }}
                </p>
                {% for post in posts %}
                    <article>
                        <ul>
                            <li>Автор: {{ post.author.get_full_name }}</li>
                            <li>Дата публикации: {{ post.pub_date|date:"d F Y" }}</li>
                        </ul>
                        <p>{{ post.text }}</p>


                    </article>
                    {% if not forloop.last %}
                        <hr>
                    {% endif %}
                {% endfor %}

            </div>

        </main>
        </body>
    {% endblock content %}

yatube/templates/posts/index.html
{% extends "base.html" %}
{% load static %}
{% load uglify %}

<!DOCTYPE html> <!-- Используется html 5 версии -->
<html lang="ru"> <!-- Язык сайта - русский -->
<head>
    {% block title %}
        <title>{{ title | uglify }}</title>
    {% endblock title %}
</head>
<body>
{% block content %}
    <main>

        <!-- класс py-5 создает отступы сверху и снизу блока -->
        <div class="container py-5">
            <h1>Последние обновления на сайте</h1>
            {% for post in page_obj %}
                <article>
                    <ul>
                        <li>Автор: {{ post.author.get_full_name }}</li>
                        <li>Дата публикации: {{ post.pub_date|date:"d F Y" }}</li>
                    </ul>
                    <p>{{ post.text }}</p>
                    <p>{{ post.group }}</p>
                    {% if post.group.address %}
                        <a href="{% url 'post:group' post.group.address %}">Перейти к сообществу</a>
                    {% endif %}

                </article>
                <a href="{% url 'post:post_detail' post.id %}">подробная информация</a>

                {% if not forloop.last %}
                    <hr>
                {% endif %}
            {% endfor %}

            <!-- под последним постом нет линии -->
        </div>

    </main>
{% endblock content %}
<!-- Использованы классы бустрапа: -->
<!-- border-top: создаёт тонкую линию сверху блока -->
<!-- text-center: выравнивает текстовые блоки внутри блока по центру -->
<!-- py-3: контент внутри размещается с отступом сверху и снизу -->

yatube/templates/posts/post_detail.html
{% extends "base.html" %}
{% load  static %}

<!DOCTYPE html>
<html lang="ru">
<head>
    {% block title %}
        <title>Пост {{ post.text|truncatechars:9 }}</title>
    {% endblock %}
</head>
<body>
{% block content %}

    <main>
        <div class="row">
            <aside class="col-12 col-md-3">
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">
                        Дата публикации: {{ post.pub_date }}
                    </li>
                    {% if post.group %}

                        <!-- если у поста есть группа -->
                        <li class="list-group-item">
                            Группа: {{ post.group.title }}
                            <a href="{% url "post:group" post.group.address %}">
                                все записи группы
                            </a>
                        </li>
                    {% endif %}

                    <li class="list-group-item">
                        Автор: {{ post.author.get_full_name }}
                    </li>
                    <li class="list-group-item d-flex justify-content-between align-items-center">
                        Всего постов автора: <span>{{ post_count }}</span>
                    </li>
                    <li class="list-group-item">
                        <a href="{% url "post:profile" post.author.username %}">
                            все посты пользователя
                        </a>
                    </li>
                </ul>
            </aside>
            <article class="col-12 col-md-9">
                <p>
                    {{ post.text }}
                </p>
                {% if is_author %}
                    <a class="btn btn-primary" href="{% url "post:post_update" post.id %}">
                        редактировать запись
                    </a>
                {% endif %}
            </article>
        </div>
    </main>
{% endblock %}
</body>
</html>

yatube/templates/posts/profile.html
{% extends "base.html" %}

{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <!-- Подключены иконки, стили и заполенены мета теги -->
    {% block title %}
        <title>Профайл пользователя {{ name }}</title>
    {% endblock %}
</head>
<body>
{% block  content %}

    <main>
        <div class="container py-5">
            <h1>Все посты пользователя {{ name }} </h1>
            <h3>Всего постов: {{ posts_count }} </h3>
            <article>
                {% for post in page_obj %}
                    <ul>
                        <li>
                            Автор: {{ post.author }}
                            <p>
                                <a href="{% url 'post:profile' post.author.username %}">все посты пользователя</a>
                            </p>
                        </li>
                        <li>
                            Дата публикации: {{ post.pub_date }}
                        </li>
                    </ul>
                    <p>
                        {{ post.text }}
                    </p>
                    <p>
                        {% if post.group.address %}
                            <a href="{% url 'post:post_detail' post.id %}">Подробная информация</a>
                        {% endif %}
                    </p>
                    {% if post.group.address %}
                        <a href="{% url 'post:group' post.group.address %}">Перейти к сообществу</a>
                    {% endif %}
                    {% if not forloop.last %}
                        <hr>
                    {% endif %}
                {% endfor %}

            </article>

            <!-- Остальные посты. после последнего нет черты -->
            <!-- Здесь подключён паджинатор -->
        </div>
    </main>
{% endblock %}

</body>
</html>