yatube/post/urls.py
from django.urls import path

from . import views

app_name = 'post'
urlpatterns = [
    path('', views.index, name="main"),
    path('group/<slug:group_name>/', views.group_posts, name='group'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('posts/create/', views.CreatePostView.as_view(), name='post_create'),
    path("posts/<int:post_id>/edit/", views.EditPostView.as_view(), name="post_update"),
]

yatube/users/urls.py
from django.contrib.auth.views import LogoutView, LoginView, PasswordChangeView, PasswordChangeDoneView
from django.urls import path

from . import views

app_name = 'users'
urlpatterns = [
    path('logout/', LogoutView.as_view(template_name='users/logged_out.html'), name='logout'),
    path('login/', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('password_change/', PasswordChangeView.as_view(template_name='users/password_change_form.html'),
         name='change_password'),
    path('password_change/done/', PasswordChangeDoneView.as_view(template_name='users/password_change_done.html'),
         name='change_password_done'),

    # path('login/', LoginView.as_view(template_name='users/../templates/registration/login.html'), name='login'),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import path, include

# yatube/url.py
urlpatterns = [
    path('auth/', include('users.urls', namespace='users')),
    path('', include('post.urls', namespace='post')),
    path('admin/', admin.site.urls),
    path('auth/', include('django.contrib.auth.urls')),
    path('library/', include('library.urls', namespace='library')),
    path('about/', include('about.urls', namespace='about')),

]

yatube/users/models.py
from django.db import models

from .validators import validate_not_empty


# Create your models here.
class Contact(models.Model):
    name = models.CharField(max_length=100, validators=[validate_not_empty, ])
    email = models.EmailField()
    subject = models.CharField(max_length=100)
    body = models.TextField(validators=[validate_not_empty, ])
    is_answered = models.BooleanField(default=False)

yatube/users/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from .models import Contact
from django import forms

User = get_user_model()


class CreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('first_name', 'last_name', 'username', 'email')


class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ('name', 'email', 'subject', 'body')

    def clean_subject(self):
        data = self.cleaned_data['subject']
        if 'thanks' not in data.lower().strip():
            raise forms.ValidationError('Поблагодарите меня')
        return data

yatube/users/views.py
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.views import PasswordChangeView
from django.core.mail import send_mail
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView
from django.views import View
from .forms import CreationForm, ContactForm
from django import forms


# Create your views here.
class SignUp(CreateView):
    form_class = CreationForm
    success_url = reverse_lazy('post:main')
    template_name = 'users/signup.html'


class UserChangePassword(PasswordChangeView):
    form_class = PasswordChangeForm
    success_url = reverse_lazy("password_change_done")
    template_name = "users/password_change_form.html"

    def form_valid(self, form):
        print('отправил форму')
        send_mail('Yatube-change_password',
                  'Вы изменили пароль в своей учетной записи',
                  'popki@mail.com',
                  [self.request.user.email])
        return super().form_valid(form)


class UserContact(View):
    template_name = 'users/contact.html'

    def get(self, request):
        form = ContactForm()
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = ContactForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            email = form.cleaned_data['email']
            subject = form.cleaned_data['subject']
            message = form.cleaned_data['body']
            form.save()
            return redirect('/thank-you/')

        return render(request, self.template_name, {'form': form})

yatube/templates/users/logged_out.html
{% extends "base.html" %}
<!DOCTYPE html>
<html lang="ru">
<head>
    {% block title %}
        <title>Вы вышли из системы</title>
    {% endblock title %}
</head>
<body>
<header>
    {% block content %}
        <nav class="navbar navbar-light" style="background-color: lightskyblue">
            <div class="container">
                <a class="navbar-brand" href="">
                    <img src="../img/logo.png" width="30" height="30" class="d-inline-block align-top" alt="">
                    <span style="color:red">Ya</span>tube
                </a>
            </div>
        </nav>
        </header>
        <main>
            <div class="container py-5">
                <div class="row justify-content-center">
                    <div class="col-md-8 p-5">
                        <div class="card">
                            <div class="card-header">Выход</div>
                            <div class="card-body"><p>Вы вышли из своей учётной записи. Ждём вас снова!</p>
                            </div> <!-- card body -->
                        </div> <!-- card -->
                    </div> <!-- col -->
                </div> <!-- row -->
            </div>
        </main>
        <footer class="border-top text-center py-3">
            <p>© 2021 Copyright <span style="color:red">Ya</span>tube</p>
        </footer>
        </body>
    {% endblock content %}
</html>

yatube/templates/users/login.html
{% extends "base.html" %}
<!DOCTYPE html>
<html lang="ru">
<head>
    {% block title %}
        <title>Войти</title>
    {% endblock title %}
</head>
<body>
{% block content %}

    <main>
        <div class="container py-5">
            <div class="row justify-content-center">
                <div class="col-md-8 p-5">
                    <div class="card">
                        <div class="card-header">
                            Войти на сайт
                        </div>
                        <div class="card-body">
                            <form method="post" action="{% url "users:login" %}">
                                <input type="hidden" name="next" value="{% url 'post:main' %}">
                                {% csrf_token %}
                                <div class="form-group row my-3">
                                    <label for="id_username">
                                        Имя пользователя
                                        <span class="required text-danger">*</span>
                                    </label>
                                    <input type="text" name="username" autofocus class="form-control" required
                                           id="id_username">
                                </div>
                                <div class="form-group row my-3">
                                    <label for="id_password">
                                        Пароль
                                        <span class="required text-danger">*</span>
                                    </label>
                                    <input type="password" name="password" class="form-control" required
                                           id="id_password">
                                </div>
                                <div class="col-md-6 offset-md-4">
                                    <button type="submit" class="btn btn-primary">
                                        Войти
                                    </button>
                                    <a href="{% url "users:change_password" %}" class="btn btn-link">
                                        Забыли пароль?
                                    </a>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock content %}

</body>
</html>

yatube/templates/users/password_change_done.html
{% extends "base.html" %}

<!DOCTYPE html>
<html lang="ru">
<head>
    {% block title %}
        <title>Пароль изменён</title>
    {% endblock title %}
</head>
<body>
<header>
    {% block content %}

        </header>
        <main>
            <div class="container py-5">
                <div class="row justify-content-center">
                    <div class="col-md-8 p-5">
                        <div class="card">
                            <div class="card-header">
                                Пароль изменён
                            </div>
                            <div class="card-body">
                                <p>Пароль изменён успешно</p>
                            </div> <!-- card body -->
                        </div> <!-- card -->
                    </div> <!-- col -->
                </div> <!-- row -->
            </div>
        </main>
        </body>
    {% endblock content %}
</html>

yatube/templates/users/password_change_form.html
{% extends "base.html" %}
<!DOCTYPE html>
<html lang="ru">
<head>
    {% block title %}
        <title>Изменение пароля</title>
    {% endblock title %}
</head>
<body>
{% block content %}

    <main>
        <div class="container py-5">
            <div class="row justify-content-center">
                <div class="col-md-8 p-5">
                    <div class="card">
                        <div class="card-header">
                            Изменить пароль
                        </div>
                        <div class="card-body">
                            <form method="post" action="{% url 'users:change_password' %}">
                                {% csrf_token %}
                                <div class="form-group row my-3 p-3">
                                    <label for="id_old_password">
                                        Старый пароль
                                        <span class="required text-danger">*</span>
                                    </label>
                                    <input type="password" name="old_password" autofocus class="form-control" required
                                           id="id_old_password">
                                </div>
                                <div class="form-group row my-3 p-3">
                                    <label for="id_new_password1">
                                        Новый пароль
                                        <span class="required text-danger">*</span>
                                    </label>
                                    <input type="password" name="new_password1" class="form-control" required
                                           id="id_new_password1">
                                    <small id="id_new_password1-help" class="form-text text-muted">
                                        <ul>
                                            <li>Ваш пароль не должен совпадать с вашим именем или другой персональной
                                                информацией или быть слишком похожим на неё.
                                            </li>
                                            <li>Ваш пароль должен содержать как минимум 8 символов.</li>
                                            <li>Ваш пароль не может быть одним из широко распространённых паролей.</li>
                                            <li>Ваш пароль не может состоять только из цифр.</li>
                                        </ul>
                                    </small>
                                </div>
                                <div class="form-group row my-3 p-3">
                                    <label for="id_new_password2">
                                        Подтверждение нового пароля
                                        <span class="required text-danger">*</span>
                                    </label>
                                    <input type="password" name="new_password2" class="form-control" required
                                           id="id_new_password2">
                                </div>
                                <div class="col-md-6 offset-md-4">
                                    <button type="submit" class="btn btn-primary">
                                        Изменить пароль
                                    </button>
                                </div>
                            </form>
                        </div> <!-- card body -->
                    </div> <!-- card -->
                </div> <!-- col -->
            </div> <!-- row -->
        </div>
    </main>
{% endblock content %}

</body>
</html>

yatube/templates/users/password_reset_complete.html
<!DOCTYPE html> 
<html lang="ru"> 
  <head>    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="../img/fav/fav.ico" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="../img/fav/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="../img/fav/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="../img/fav/favicon-16x16.png">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">
    <link rel="stylesheet" href="../css/bootstrap.min.css">
    <title>Сброс пароля прошёл успешно</title>
  </head>
  <body>	   
    <header>
      <nav class="navbar navbar-light" style="background-color: lightskyblue">
        <div class="container">
          <a class="navbar-brand" href="">
            <img src="../img/logo.png" width="30" height="30" class="d-inline-block align-top" alt="">
            <span style="color:red">Ya</span>tube
          </a>        
        </div>
      </nav> 
    </header>
    <main>
      <div class="container py-5"> 
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
                Восстановление пароля завершено
              </div>
              <div class="card-body">
                <p>Ваш пароль был сохранен. Используйте его для входа</p>
                <a href="../users/login.html">войти</a>
              </div> 
            </div> 
          </div>
        </div> 
      </div>
    </main>
	  <footer class="border-top text-center py-3">
      <p>© 2021 Copyright <span style="color:red">Ya</span>tube</p>    
    </footer>
  </body>
</html>

yatube/templates/users/password_reset_confirm.html
<!DOCTYPE html> 
<html lang="ru"> 
  <head>    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="../img/fav/fav.ico" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="../img/fav/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="../img/fav/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="../img/fav/favicon-16x16.png">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">
    <link rel="stylesheet" href="../css/bootstrap.min.css">
    <title>Новый пароль</title>
  </head>
  <body>	   
    <header>
      <nav class="navbar navbar-light" style="background-color: lightskyblue">
        <div class="container">
          <a class="navbar-brand" href="">
            <img src="../img/logo.png" width="30" height="30" class="d-inline-block align-top" alt="">
            <span style="color:red">Ya</span>tube
          </a>        
        </div>
      </nav> 
    </header>
    <main>
      <div class="container py-5"> 
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
                Введите новый пароль
              </div>
              <div class="card-body">
                <form method="post" action="../users/lpassword_reset_confirm.html">

                  <input type="hidden" name="csrfmiddlewaretoken" value="">
                  <div class="form-group row my-3 p-3">
                    <label for="id_new_password1">
                      Новый пароль        
                      <span class="required text-danger">*</span>        
                    </label>    
                    <input type="password" name="new_password1" class="form-control" required id="id_new_password1">      
                    <small id="id_new_password1-help" class="form-text text-muted">
                      <ul><li>Ваш пароль не должен совпадать с вашим именем или другой персональной информацией или быть слишком похожим на неё.</li><li>Ваш пароль должен содержать как минимум 8 символов.</li><li>Ваш пароль не может быть одним из широко распространённых паролей.</li><li>Ваш пароль не может состоять только из цифр.</li></ul>
                    </small>      
                  </div>
                  <div class="form-group row my-3 p-3">
                    <label for="id_new_password2">
                      Подтверждение нового пароля        
                      <span class="required text-danger">*</span>        
                    </label>    
                    <input type="password" name="new_password2" class="form-control" required id="id_new_password2">      
                  </div>
                  <div class="col-md-6 offset-md-4">
                    <button type="submit" class="btn btn-primary">
                      Назначить новый пароль
                    </button>
                  </div>
                </form>
              </div> <!-- card body -->
            </div> <!-- card -->
          </div> <!-- col -->
        </div> <!-- row -->
        <!-- если использована неправильная ссылка -->
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
                Ошибка
              </div>
              <div class="card-body">
                <p>Ссылка сброса пароля содержит ошибку или устарела.</p>
              </div> <!-- card body -->
            </div> <!-- card -->
          </div> <!-- col -->
        </div> <!-- row -->
        <!-- конец если использована неправильная ссылка -->
      </div>
    </main>
	  <footer class="border-top text-center py-3">
      <p>© 2021 Copyright <span style="color:red">Ya</span>tube</p>    
    </footer>
  </body>
</html>

yatube/templates/users/password_reset_done.html
<!DOCTYPE html> 
<html lang="ru"> 
  <head>    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="../img/fav/fav.ico" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="../img/fav/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="../img/fav/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="../img/fav/favicon-16x16.png">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">
    <link rel="stylesheet" href="../css/bootstrap.min.css">
    <title>Сброс пароля прошёл успешно</title>
  </head>
  <body>	   
    <header>
      <nav class="navbar navbar-light" style="background-color: lightskyblue">
        <div class="container">
          <a class="navbar-brand" href="">
            <img src="../img/logo.png" width="30" height="30" class="d-inline-block align-top" alt="">
            <span style="color:red">Ya</span>tube
          </a>        
        </div>
      </nav> 
    </header>
    <main>
      <div class="container py-5"> 
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
                Отправлено письмо
              </div>
              <div class="card-body">
                <p>Проверьте свою почту, вам должно прийти письмо со ссылкой для восстановления пароля</p>
              </div> 
            </div> 
          </div>
        </div> 
      </div>
    </main>
	  <footer class="border-top text-center py-3">
      <p>© 2021 Copyright <span style="color:red">Ya</span>tube</p>    
    </footer>
  </body>
</html>

yatube/templates/users/password_reset_form.html
<!DOCTYPE html> 
<html lang="ru"> 
  <head>    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="../img/fav/fav.ico" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="../img/fav/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="../img/fav/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="../img/fav/favicon-16x16.png">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">
    <link rel="stylesheet" href="../css/bootstrap.min.css">
    <title>Сброс пароля</title>
  </head>
  <body>	   
    <header>
      <nav class="navbar navbar-light" style="background-color: lightskyblue">
        <div class="container">
          <a class="navbar-brand" href="">
            <img src="../img/logo.png" width="30" height="30" class="d-inline-block align-top" alt="">
            <span style="color:red">Ya</span>tube
          </a>        
        </div>
      </nav> 
    </header>
    <main>
      <div class="container py-5"> 
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
                Чтобы сбросить старый пароль — введите адрес электронной почты, под которым вы регистрировались
              </div>
              <div class="card-body"> 
                <form method="post" action="../users/password_reset_form.html">
                  <input type="hidden" name="csrfmiddlewaretoken" value="">
                  <div class="form-group row my-3 p-3">
                    <label for="id_email">
                      Адрес электронной почты
                      <span class="required text-danger">*</span>
                    </label>    
                    <input type="email" name="email" maxlength="254" class="form-control" required id="id_email">
                  </div>
                  <div class="col-md-6 offset-md-4">
                    <button type="submit" class="btn btn-primary">
                      Сбросить пароль
                    </button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>  
      </div>
    </main>
	  <footer class="border-top text-center py-3">
      <p>© 2021 Copyright <span style="color:red">Ya</span>tube</p>    
    </footer>
  </body>
</html>

yatube/templates/users/signup.html
{% extends "base.html" %}
{% block title %}Зарегистрироваться{% endblock %}
{% block content %}
    <div class="row justify-content-center">
        <div class="col-md-8 p-5">
            <div class="card">
                <div class="card-header">Зарегистрироваться</div>
                <div class="card-body">
                    {% load user_filters %} {# Загружаем фильтры #}
                    {% if form.errors %}
                        {% for field in form %}
                            {% for error in field.errors %}
                                <div class="alert alert-danger">
                                    {{ error|escape }}
                                </div>
                            {% endfor %}
                        {% endfor %}
                        {% for error in form.non_field_errors %}
                            <div class="alert alert-danger">
                                {{ error|escape }}
                            </div>
                        {% endfor %}
                    {% endif %}

                    <form method="post" action="{% url 'users:signup' %}">
                        {% csrf_token %}

                        {# Выводим поля в цикле, по отдельности #}
                        {% for field in form %}
                            <div class="form-group row my-3">
                                <label for="{{ field.id_for_label }}">
                                    {{ field.label }}
                                    {% if field.field.required %}
                                        <span class="required text-danger">*</span>
                                    {% endif %}
                                </label>
                                {# К полю ввода добавляем атрибут class #}
                                {{ field|add_class:"form-control" }}
                                {% if field.help_text %}
                                    <small
                                            id="{{ field.id_for_label }}-help"
                                            class="form-text text-muted"
                                    >
                                        {{ field.help_text|safe }}
                                    </small>
                                {% endif %}
                            </div>
                        {% endfor %}
                        <div class="col-md-6 offset-md-4">
                            <button type="submit" class="btn btn-primary">
                                Зарегистрироваться
                            </button>
                        </div>
                    </form>
                </div> <!-- card body -->
            </div> <!-- card -->
        </div> <!-- col -->
    </div> <!-- row -->
{% endblock %}